version: "3"
services:
    server:
        build: ./server
        container_name: server-container
        tty: true
        networks:
            msgsubnet:
                ipv4_address: 172.19.0.2
        
    client1:
        build: ./client
        container_name: client1-container
        tty: true
        networks:
            msgsubnet:
                ipv4_address: 172.19.0.3
        
    client2:
        build: ./client
        container_name: client2-container
        tty: true
        networks:
            msgsubnet:
                ipv4_address: 172.19.0.4

networks:
    msgsubnet:
        driver: "bridge"
        ipam:
            config:
              - subnet: 172.19.0.0/24
